# mongodb://root:root123.@localhost:27018 -> PARA LOCAL
# mongodb://root:root123.@mongo_api:27017 -> PARA CONTENEDORES
# mongodb://root:root123.@host.docker.internal:27018 -> PARA FLOWISE
version: '3.8'

services:
  mongo_api:
    image: mongo:latest
    container_name: mongo_stockMind
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123.
    networks:
      - service

networks:
  service:
    driver: bridge